#!/usr/bin/env python

#############################################################
# ubi_reader
# (C) Collin Mulliner based on Jason Pruitt's ubireader_extract_images
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#############################################################

import argparse
import sys

from ubireader.exceptions import UBIReaderParseError
from ubireader.parsers import list_files


if __name__=='__main__':
    parser = argparse.ArgumentParser(
        usage=list_files.usage,
        description=list_files.description,
        parents=[list_files.parser]
    )

    if len(sys.argv) == 1:
        parser.print_help()
        sys.exit(1)

    args = vars(parser.parse_args())
    func = args.pop("func")
    try:
        func(**args)
    except UBIReaderParseError as e:
        parser.error(str(e))    
